### ISSUE TITLE
chrome 62: icons are mislocated 

### ISSUE THREAD

**Issue by felipem775** [Turbo87/sidebar-v2#126]
In the new Chrome version, 62, the icons in sidebar are mislocated some pixels down.

![chrome61](https://user-images.githubusercontent.com/1591085/31761535-80c27294-b4b8-11e7-99c9-92bf88bb75bd.jpg)
![chrome62](https://user-images.githubusercontent.com/1591085/31761619-db79af04-b4b8-11e7-83d1-a71a902992dd.jpg)

**Comment by Turbo87** [comment]
Sounds like a bug in Chrome to me... 🤔

**Comment by markhepburn** [comment]
Just came to report this -- you can "fix" it by removing the overflow:hidden rule, but that's presumably pretty fragile.

**Comment by markhepburn** [comment]
Looks like this issue: https://bugs.chromium.org/p/chromium/issues/detail?id=775880

**Comment by markhepburn** [comment]
Sorry for the noise, but from the above issue the following rule might be a more robust fix:
.sidebar-tabs>li, .sidebar-tabs>ul>li {
    list-style-type: none;
}

**Comment by Turbo87** [comment]
Thanks for figuring this out @markhepburn! #127 should fix the issue until Chrome releases a fixed version.

**Comment by eric47905** [comment]
I know this issue is old and already closed, but adding this in, just in case someone else has an issue like I did. 

Opposite the icons displaying too far down, Mine were displaying all the way at the top of each 40px square. I fixed by adding some top padding to the `.sidebar-tabs > li > a, .sidebar-tabs > ul > li > a {` section.

`.sidebar-tabs > li > a, .sidebar-tabs > ul > li > a {
        display: block;
        width: 100%;
        height: 100%;
        line-height: 40px;
        color: inherit;
        text-decoration: none;
        text-align: center; 
        list-style-type: none; 
        padding-top: 10;
        padding-right: 0;
        padding-left: 0;
        padding-bottom: 0;
        }`

![misalignment pic](https://user-images.githubusercontent.com/42282130/44301960-032fd400-a2d5-11e8-8678-28123f25625e.jpg)
