### ISSUE TITLE
Can't get info tip to open sidebar on click

### ISSUE THREAD

**Issue by jerryHall** [Turbo87/sidebar-v2#61]
Great tool here. Looking forward to a full implementation with datatables. Right now I'm having trouble clicking on the icon (map pin) to open the sidebar. I tried on your example page as well and it's not working there either (for me). Thanks!

I'm using Firefox and tested in Chrome, IE and Nightly as well. 

Er, just found on StackExchange that v2 doesn't have the interactive element enabled yet. That little tidbit would've saved me a few hours :). No gripes though, working with v1 and hope to contribute to v2 as well. :+1:

**Comment by Turbo87** [comment]
not quite sure what so mean by "full implementation with datatables". sounds a bit out of scope for this plugin to be honest but could obviously be implemented on top of it.

> I tried on your example page as well and it's not working there either (for me).

That is simply because there is no action handler attached to the marker (yet), but that should be relatively easy to solve.

> just found on StackExchange that v2 doesn't have the interactive element enabled yet

what exactly do you mean by "interactive element"?

**Comment by jerryHall** [comment]
Sorry, I was mixing a couple different issues. 
My biggest interest is having the ability to use the v2 with the function of opening the sidebar when a user clicks on the map point eg on this page: http://turbo87.github.io/sidebar-v2/examples/. 

The second thing was how I take my JSON data associated with that map point and place it in the sidebar. My goal is to only show the details for one map point in the sidebar at a time. I'm (perhaps obviously) a noob and would really love to get this working in either v1 or v2 but, ideally v2. Thanks!

**Comment by Turbo87** [comment]
the first issue is pretty easy to resolve. instead of:

```js
        var marker = L.marker([51.2, 7]).addTo(map);
        var sidebar = L.control.sidebar('sidebar').addTo(map);
```

you need to write:

```js
        var sidebar = L.control.sidebar('sidebar').addTo(map);
        var marker = L.marker([51.2, 7]).addTo(map).on('click', function () {
            sidebar.open('tab-name');
        });
```

the second issue is a bit more involved but it boils down to modifying the DOM of the tab content `<div>`. easiest solution would be to modify the `innerHTML` attribute of the tab content node inside of the `click` handler function above.
