### ISSUE TITLE
Sidebar Not Working With Full Screen Control - Openlayers API 

### ISSUE THREAD

**Issue by RenoSun** [Turbo87/sidebar-v2#65]
Hi Turbo87,

I am using the sidebar-v2 for our mobile friendly GIS/Map viewer, and it works really good!!!
[Town of Qualicum Beach Zoning Map](http://maps.qualicumbeach.com/qbmap/mobileMapViewer/MobileMap.aspx?m=Property&hg=&sg=Zoning,Cadastral&sl=QBZoning,QBParcels,QBStrata&blyr=TTTFFFFF&curextent=-13860507.876893189,6329430.232239501,-13842162.990104746,6338554.902491043&zoom=14&hl=AddressPoints)

However, the sidebar is not working with "ol.control.FullScreen" with Openlayers API. The sidebar disappeared after I click the FullScreen control. Moreover, the sidebar actually works just fine if I click F11 by making my browser full-screen.

Thanks :+1:

**Comment by Turbo87** [comment]
@RenoSun the reason is that the fullscreen control will just use the map element for the full screen context, but it would need to use the element that hosts both map and sidebar since the sidebar is not part of the map element. there is not much I can do here, but maybe you could get the fullscreen control to accept a different target element or something like that.

**Comment by RenoSun** [comment]
Okay, I think I will implement my own full-screen control instead of using the default openlayers control to see if it will work with the sidebar :) Thanks!

**Comment by shaula** [comment]
Its possible with on-board options:
```
var fullscreenControl = new ol.control.FullScreen({
  source: document.getElementById('map').parentNode
});

map.addControl(fullscreenControl);
```
